/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pe.egcc.mateapp.view;

import javax.swing.JInternalFrame;

/**
 *
 * @author Alumno
 */
public class FormularioMDI extends javax.swing.JFrame {

    /**
     * Creates new form FormularioMDI
     */
    public FormularioMDI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        openMenuItem = new javax.swing.JMenuItem();
        saveMenuItem = new javax.swing.JMenuItem();
        saveAsMenuItem = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        menuMate = new javax.swing.JMenu();
        menuMatFactorial = new javax.swing.JMenuItem();
        menuMatMcdMcm = new javax.swing.JMenuItem();
        menuMatFibonacci = new javax.swing.JMenuItem();
        menuMatePrimo = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        desktopPane.setToolTipText("");

        fileMenu.setMnemonic('f');
        fileMenu.setText("File");

        openMenuItem.setMnemonic('o');
        openMenuItem.setText("Open");
        fileMenu.add(openMenuItem);

        saveMenuItem.setMnemonic('s');
        saveMenuItem.setText("Save");
        fileMenu.add(saveMenuItem);

        saveAsMenuItem.setMnemonic('a');
        saveAsMenuItem.setText("Save As ...");
        saveAsMenuItem.setDisplayedMnemonicIndex(5);
        fileMenu.add(saveAsMenuItem);

        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        menuMate.setText("Matematica");

        menuMatFactorial.setText("Factorial");
        menuMatFactorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuMatFactorialActionPerformed(evt);
            }
        });
        menuMate.add(menuMatFactorial);

        menuMatMcdMcm.setText("MCD y MCM");
        menuMatMcdMcm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuMatMcdMcmActionPerformed(evt);
            }
        });
        menuMate.add(menuMatMcdMcm);

        menuMatFibonacci.setText("Fibonacci");
        menuMatFibonacci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuMatFibonacciActionPerformed(evt);
            }
        });
        menuMate.add(menuMatFibonacci);

        menuMatePrimo.setText("Primo");
        menuMatePrimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuMatePrimoActionPerformed(evt);
            }
        });
        menuMate.add(menuMatePrimo);

        menuBar.add(menuMate);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 795, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(desktopPane, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void menuMatFactorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuMatFactorialActionPerformed
     cargarFormulario(FactorialView.class);
           
                
    }//GEN-LAST:event_menuMatFactorialActionPerformed

    private void menuMatMcdMcmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuMatMcdMcmActionPerformed
    cargarFormulario(McdMcmView.class);         
    }//GEN-LAST:event_menuMatMcdMcmActionPerformed

    private void menuMatFibonacciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuMatFibonacciActionPerformed
   cargarFormulario(FibonacciView.class);        
    }//GEN-LAST:event_menuMatFibonacciActionPerformed

    private void menuMatePrimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuMatePrimoActionPerformed
      cargarFormulario(PrimoView.class);
              
    }//GEN-LAST:event_menuMatePrimoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormularioMDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormularioMDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormularioMDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormularioMDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormularioMDI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem menuMatFactorial;
    private javax.swing.JMenuItem menuMatFibonacci;
    private javax.swing.JMenuItem menuMatMcdMcm;
    private javax.swing.JMenu menuMate;
    private javax.swing.JMenuItem menuMatePrimo;
    private javax.swing.JMenuItem openMenuItem;
    private javax.swing.JMenuItem saveAsMenuItem;
    private javax.swing.JMenuItem saveMenuItem;
    // End of variables declaration//GEN-END:variables

    private void cargarFormulario(Class<?> aClass){
        try {           
             

            //Variable
            JInternalFrame view ;
            //Buscar instancia
            view = buscarInstancia(aClass);
            //Crear instancia
            if(view == null){
            view = (JInternalFrame)Class.forName(aClass.getName()).newInstance();
               desktopPane.add(view) 
            }
            //Mostrar formulario
            view.setVisible(true);
            view.setSelected(true);
            
        }   catch ( Excepetion e){
        }
    } 
    private JInternalFrame buscarInstancia(Class<?> aClass){
        JInternalFrame view = null;
        for(JInternalFrame form: desktopPane.getAllFrames()){
            
        }
    


